Repository ros2/rmw_fastrtps, pull requests merged in 2018-06, with the labels that each got.

#201 Fix leak if client reponse is never taken
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_client_info.hpp
  rmw_fastrtps_cpp/src/rmw_response.cpp
Labels: bug, in review

#192 Remove topic partitions
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/reader_info.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/writer_info.hpp
  rmw_fastrtps_cpp/src/assign_partitions.hpp
  rmw_fastrtps_cpp/src/rmw_client.cpp
  rmw_fastrtps_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_cpp/src/rmw_service.cpp
  rmw_fastrtps_cpp/src/rmw_service_server_is_available.cpp
  rmw_fastrtps_cpp/src/rmw_subscription.cpp
Labels: in review

#206 use size_t
  rmw_fastrtps_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_cpp/src/rmw_take.cpp
Labels: in progress

#186 Expose raw CDR stream for publish and subscribe
  rmw_fastrtps_cpp/CMakeLists.txt
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
  rmw_fastrtps_cpp/src/rmw_publish.cpp
  rmw_fastrtps_cpp/src/rmw_request.cpp
  rmw_fastrtps_cpp/src/rmw_response.cpp
  rmw_fastrtps_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_cpp/src/rmw_take.cpp
  rmw_fastrtps_cpp/src/ros_message_serialization.cpp
  rmw_fastrtps_cpp/src/ros_message_serialization.hpp
Labels: in progress

#208 update usage of rcutils_join_path()
  rmw_fastrtps_cpp/src/rmw_node.cpp
Labels: in review

#210 Validate the buffer_ of CustomServiceRequest object before using it to
  rmw_fastrtps_cpp/src/rmw_request.cpp
Labels: in review

#207 Temporary buffer remove
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport_impl.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport_impl.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
  rmw_fastrtps_cpp/src/rmw_publish.cpp
  rmw_fastrtps_cpp/src/rmw_request.cpp
  rmw_fastrtps_cpp/src/rmw_response.cpp
  rmw_fastrtps_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_cpp/src/ros_message_serialization.cpp
  rmw_fastrtps_cpp/src/ros_message_serialization.hpp
Labels: enhancement, in review

#211 Avoid allocations
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport_impl.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport_impl.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_client_info.hpp
  rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_service_info.hpp
  rmw_fastrtps_cpp/src/rmw_publish.cpp
  rmw_fastrtps_cpp/src/rmw_request.cpp
  rmw_fastrtps_cpp/src/rmw_response.cpp
  rmw_fastrtps_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_cpp/src/rmw_take.cpp
  rmw_fastrtps_cpp/src/ros_message_serialization.cpp
  rmw_fastrtps_cpp/src/ros_message_serialization.hpp
Labels: in review

#213 Prepare 0.5.0
  fastrtps_cmake_module/package.xml
  rmw_fastrtps_cpp/package.xml
Labels: in progress, in review
