Repository ros2/rmw_fastrtps, pull requests merged in 2018-11, with the labels that each got.

#231 use new error handling API from rcutils
  rmw_fastrtps_shared_cpp/src/rmw_node_names.cpp
  rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
  rmw_fastrtps_shared_cpp/src/rmw_service_names_and_types.cpp
  rmw_fastrtps_shared_cpp/src/rmw_take.cpp
  rmw_fastrtps_shared_cpp/src/rmw_topic_names_and_types.cpp
Labels: enhancement, in review

#232 rename dynamic array to sequence
  rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
  rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/macros.hpp
Labels: in review

#240 use uint8_array
  rmw_fastrtps_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
Labels: in progress

#242 Fixing failing tests on rmw_fastrtps_dynamic_cpp.
  rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
  rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
Labels: in review

#234 Methods to retrieve matched counts on pub/sub
  rmw_fastrtps_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_publisher_info.hpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
  rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
Labels: in review

#237 refactor to support init options and context
  rmw_fastrtps_cpp/src/rmw_guard_condition.cpp
  rmw_fastrtps_cpp/src/rmw_init.cpp
  rmw_fastrtps_cpp/src/rmw_node.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_guard_condition.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
Labels: enhancement, in progress, in review
