Repository ros2/rmw_fastrtps, pull requests merged in 2019-05, with the labels that each got.

#274 Updates for preallocation API.
  rmw_fastrtps_cpp/src/rmw_publish.cpp
  rmw_fastrtps_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_cpp/src/rmw_take.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_publish.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_take.cpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
  rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
  rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Labels: in progress

#271 Add qos interfaces with no-op
  rmw_fastrtps_cpp/CMakeLists.txt
  rmw_fastrtps_cpp/src/qos.cpp
  rmw_fastrtps_cpp/src/rmw_client.cpp
  rmw_fastrtps_cpp/src/rmw_node.cpp
  rmw_fastrtps_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_cpp/src/rmw_service.cpp
  rmw_fastrtps_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_cpp/src/rmw_take.cpp
  rmw_fastrtps_cpp/src/rmw_wait.cpp
  rmw_fastrtps_dynamic_cpp/CMakeLists.txt
  rmw_fastrtps_dynamic_cpp/src/qos.cpp
  rmw_fastrtps_dynamic_cpp/src/qos.hpp
  rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_take.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_wait.cpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
  rmw_fastrtps_shared_cpp/src/qos.cpp
  rmw_fastrtps_shared_cpp/src/qos.hpp
  rmw_fastrtps_shared_cpp/src/rmw_client.cpp
  rmw_fastrtps_shared_cpp/src/rmw_node.cpp
  rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_shared_cpp/src/rmw_service.cpp
  rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_shared_cpp/src/rmw_take.cpp
  rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
Labels: in review

#276 Set more correct return values for unimplemented features (QoS)
  rmw_fastrtps_shared_cpp/src/rmw_take.cpp
  rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
Labels: in progress

#266 Support arbitrary message namespaces
  rmw_fastrtps_cpp/src/rmw_client.cpp
  rmw_fastrtps_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_cpp/src/rmw_service.cpp
  rmw_fastrtps_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_cpp/src/type_support_common.cpp
  rmw_fastrtps_cpp/src/type_support_common.hpp
  rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/MessageTypeSupport_impl.hpp
  rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/ServiceTypeSupport_impl.hpp
  rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_dynamic_cpp/src/type_support_common.hpp
  rmw_fastrtps_shared_cpp/src/demangle.cpp
Labels: in review

#272 Upgrades to support Fast-RTPS 1.8.0
  rmw_fastrtps_cpp/src/rmw_client.cpp
  rmw_fastrtps_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_cpp/src/rmw_service.cpp
  rmw_fastrtps_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/names.hpp
  rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
Labels: in progress

#278 add support for WString in rmw_fastrtps_dynamic_cpp
  rmw_fastrtps_dynamic_cpp/CMakeLists.txt
  rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
  rmw_fastrtps_dynamic_cpp/package.xml
Labels: enhancement, in review

#275 Fastrtps18 event callbacks policies
  rmw_fastrtps_shared_cpp/CMakeLists.txt
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_event_info.hpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_publisher_info.hpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp
  rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp
  rmw_fastrtps_shared_cpp/src/custom_subscriber_info.cpp
  rmw_fastrtps_shared_cpp/src/qos.cpp
  rmw_fastrtps_shared_cpp/src/rmw_take.cpp
  rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
Labels: enhancement, in progress

#283 Fixing data race on custom_participant_info.
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
Labels: bug, in review
