Repository ros2/rmw_fastrtps, pull requests merged in 2019-01, with the labels that each got.

#250 remove duplicate namespace_prefix symbols
  rmw_fastrtps_cpp/CMakeLists.txt
  rmw_fastrtps_cpp/src/namespace_prefix.cpp
  rmw_fastrtps_cpp/src/namespace_prefix.hpp
  rmw_fastrtps_cpp/src/rmw_client.cpp
  rmw_fastrtps_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_cpp/src/rmw_service.cpp
  rmw_fastrtps_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_dynamic_cpp/CMakeLists.txt
  rmw_fastrtps_dynamic_cpp/src/namespace_prefix.cpp
  rmw_fastrtps_dynamic_cpp/src/namespace_prefix.hpp
  rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/namespace_prefix.hpp
  rmw_fastrtps_shared_cpp/src/demangle.cpp
  rmw_fastrtps_shared_cpp/src/namespace_prefix.cpp
  rmw_fastrtps_shared_cpp/src/rmw_client.cpp
  rmw_fastrtps_shared_cpp/src/rmw_count.cpp
  rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
  rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_shared_cpp/src/rmw_service.cpp
  rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_shared_cpp/src/rmw_topic_names_and_types.cpp
Labels: bug, in review

#238 Improve service_is_available logic to protect that client is waiting …
  rmw_fastrtps_cpp/src/rmw_client.cpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
  rmw_fastrtps_shared_cpp/src/rmw_client.cpp
  rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
Labels: enhancement, in review

#254 Add missing logic to dynamic RMW client implementation
  rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
Labels: in review

#252 pass context to wait set and fini context
  rmw_fastrtps_cpp/src/rmw_init.cpp
  rmw_fastrtps_cpp/src/rmw_wait_set.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_wait_set.cpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
  rmw_fastrtps_shared_cpp/src/rmw_wait_set.cpp
Labels: in review
