Repository ros2/rmw_fastrtps, pull requests merged in 2020-09, with the labels that each got.

#429 Avoid memory leaks and undefined behavior in rmw_fastrtps_dynamic_cpp typesupport code
  rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport.hpp
  rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
Labels: bug

#437 Make sure type can be unregistered successfully
  rmw_fastrtps_cpp/src/subscription.cpp
  rmw_fastrtps_dynamic_cpp/src/subscription.cpp
Labels: bug

#448 Fix array `get_function` semantics
  rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
Labels: bug

#442 Added rmw_logging tests
  rmw_fastrtps_cpp/CMakeLists.txt
  rmw_fastrtps_cpp/test/test_logging.cpp
  rmw_fastrtps_dynamic_cpp/CMakeLists.txt
  rmw_fastrtps_dynamic_cpp/test/test_logging.cpp
  rmw_fastrtps_shared_cpp/test/CMakeLists.txt
  rmw_fastrtps_shared_cpp/test/test_logging.cpp
Labels: tests

#443 Updated rmw_* return codes
  rmw_fastrtps_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_cpp/src/rmw_wait.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_wait.cpp
  rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
  rmw_fastrtps_shared_cpp/src/listener_thread.cpp
  rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
  rmw_fastrtps_shared_cpp/src/rmw_wait_set.cpp
Labels: enhancement

#451 Checked client implementation and return RMW_RET_INCORRECT_RMW_IMPLEMENTATION in rmw_service_server_is_available
  rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
Labels: enhancement

#452 Return RMW_RET_UNSUPPORTED in rmw_get_serialized_message_size
  rmw_fastrtps_cpp/src/rmw_serialize.cpp
  rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
Labels: tests
